name: asr
dependencies:
  - python=3.7
  - click==7.1.2
  - tensorflow==1.14.0
  - pandas==1.0.3
  - matplotlib==3.1.1
  - numpy==1.16.4
  - glob2==0.7
  - tqdm==4.46.0
  - python_speech_features==0.6
  - pip:
      - librosa==0.7.2
      - wget==3.2
